### ISSUE TITLE
Suggestions for topic and tags

### ISSUE THREAD

**Issue by Yakumo-Yukari** [ngocphuongnb/tetua#2]
![a](https://user-images.githubusercontent.com/12076232/169010272-405f3fea-095c-46f7-8131-a19a0f41869d.png)

When posting, perhaps the topic or category should be selected as a single choice instead of multiple choices, perhaps adding a custom tag feature

Uh uh uh, this is just my personal opinion maybe you will have a better idea

**Comment by Yakumo-Yukari** [comment]
Another problem about empty comments, when the comment is submitted empty, it will jump to prompt '[{"type": "error", "message": "Content is required"}]' without the message reminding the user that the comment cannot be empty

**Comment by ngocphuongnb** [comment]
Thank you, I appreciate your suggestion. Maybe i will seperate the "name" and the "content" fields for more clear message
