### ISSUE TITLE
setup?

### ISSUE THREAD

**Issue by alst-ovh** [ngocphuongnb/tetua#6]
./tetua setup -u root -p 123
2022/07/07 17:18:28 dial tcp 127.0.0.1:3000: connect: connection refused

Cant start setup, whats wrong ?

{
  "app_env": "production",
  "app_key": "BpLnfgDsc2WD8F2qNfHK5a84jjJkwzDk",
  "app_base_url": "http://localhost:3000",
  "db_dsn": "root:123@tcp(127.0.0.1:3000)/tetua?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=true",
  "db_query_logging": true,
  "show_tetua_block": true,
  "mail": {
    "sender": "sender@site.local",
    "smtp": {
      "host": "smtp.service.local",
      "port": 465,
      "secure": true,
      "user": "sender@site.local",
      "pass": "smtp_password"
    }
  },
  "auth": {
    "enabled_providers": ["github", "google", "twitter"],
    "providers": {
      "github": {
        "client_id": "github_client_id",
        "client_secret": "github_client_secret"
      },
      "google": {
        "client_id": "google_client_id",
        "client_secret": "google_client_secret"
      },
      "twitter": {
        "consumer_key": "twitter_consumer_key",
        "consumer_secret": "twitter_consumer_secret"
      }
    }
  },
  "storage": {
    "default_disk": "my_disk",
    "disks": [
      {
        "name": "my_disk",
        "driver": "local",
        "root": "./public",
        "provider": "local",
        "base_url": "http://localhost:3000/storage/"
      }
    ]
  }
}

**Comment by ngocphuongnb** [comment]
@alst-ovh sorry for the late response.
Your configuration file appears to be incorrect at the `db dsn`. The application port is 3000, which you are using. You must use the mysql port here, which is usually 3306, so the configuration should be as follows:
`root:123@tcp(127.0.0.1:3306)/tetua?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=true`

**Comment by ngocphuongnb** [comment]
I'm closing this issue; please open a new one if you have any further questions.
